name: Create Pull Request

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      source:
        required: true
        type: string
      runs-on:
        description: 'Sets the run environment (default is ubuntu 22.04)'
        required: false
        type: string
        default: 'ubuntu-22.04'

jobs:
  createPullRequest:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.source }}
      - name: Download PR template
        run: |
          mkdir -p .github
          curl https://raw.githubusercontent.com/thebitrebels/.github/master/PULL_REQUEST_TEMPLATE.md -o .github/PULL_REQUEST_TEMPLATE.md
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: 'PR: ${{ inputs.source }} into ${{ inputs.target }}'
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
          pr_assignee: ${{ github.actor }}
          pr_label: draft
          destination_branch: ${{ inputs.target }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
