name: Deploy

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build image
      run: docker buildx build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:${{ inputs.tag }} --label "runnumber=${{ inputs.tag }}-${GITHUB_RUN_ID}"
    - name: Push image
      run: docker push ghcr.io/${{ github.repository }} --all-tags
