name: Build

on:
  workflow_call:
    inputs:
      path:
        description: 'Path to Dockerfile'
        required: false
        type: string
        default: 'Dockerfile'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image
      run: docker buildx build . --file ${{ inputs.path }}
