name: Build

on:
  workflow_call:
    inputs:
      path:
        description: 'Path to Dockerfile (default is Dockerfile)'
        required: false
        type: string
        default: 'Dockerfile'
      runs-on:
        description: 'Sets the run environment (default is ubuntu 20.04)'
        required: false
        type: string
        default: 'ubuntu-20.04'

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image
      run: docker buildx build . --file ${{ inputs.path }}
